# flye/tests/data/ecoli_500kb_reads.fastq.gz
reads_file=flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz
# reads_file=flye/tests/data/ecoli_500kb.fasta
out_dir=o
rm -rf ${out_dir}
bin/flye --pacbio-corr $reads_file --debug -g 500k -o $out_dir -t 8 -m 1000
exit

flye-modules assemble --reads /home/goshng/all/polap/Flye/flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz --out-asm /home/goshng/all/polap/Flye/o/00-assembly/draft_assembly.fasta --config /home/goshng/all/polap/Flye/flye/config/bin_cfg/asm_corrected_reads.cfg --log /home/goshng/all/polap/Flye/o/flye.log --threads 8 --debug --genome-size 500000 --min-ovlp 1000
flye-minimap2 '/home/goshng/all/polap/Flye/o/00-assembly/draft_assembly.fasta' '/home/goshng/all/polap/Flye/flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz' -x map-pb -t 8 -a -p 0.5 -N 10 --sam-hit-only -L -K 1G -z 1000 -Q --secondary-seq -I 64G | flye-samtools view -T '/home/goshng/all/polap/Flye/o/00-assembly/draft_assembly.fasta' -u - | flye-samtools sort -T '/home/goshng/all/polap/Flye/o/10-consensus/sort_241207_112403' -O bam -@ 4 -l 1 -m 1G -o '/home/goshng/all/polap/Flye/o/10-consensus/minimap.bam'
flye-modules repeat --disjointigs /home/goshng/all/polap/Flye/o/10-consensus/consensus.fasta --reads /home/goshng/all/polap/Flye/flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz --out-dir /home/goshng/all/polap/Flye/o/20-repeat --config /home/goshng/all/polap/Flye/flye/config/bin_cfg/asm_corrected_reads.cfg --log /home/goshng/all/polap/Flye/o/flye.log --threads 8 --debug --min-ovlp 1000
flye-modules contigger --graph-edges /home/goshng/all/polap/Flye/o/20-repeat/repeat_graph_edges.fasta --reads /home/goshng/all/polap/Flye/flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz --out-dir /home/goshng/all/polap/Flye/o/30-contigger --config /home/goshng/all/polap/Flye/flye/config/bin_cfg/asm_corrected_reads.cfg --repeat-graph /home/goshng/all/polap/Flye/o/20-repeat/repeat_graph_dump --graph-aln /home/goshng/all/polap/Flye/o/20-repeat/read_alignment_dump --log /home/goshng/all/polap/Flye/o/flye.log --threads 8 --debug --min-ovlp 1000
flye-minimap2 '/home/goshng/all/polap/Flye/o/30-contigger/contigs.fasta' '/home/goshng/all/polap/Flye/flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz' -x map-pb -t 8 -a -p 0.5 -N 10 --sam-hit-only -L -K 1G -z 1000 -Q --secondary-seq -I 64G | flye-samtools view -T '/home/goshng/all/polap/Flye/o/30-contigger/contigs.fasta' -u - | flye-samtools sort -T '/home/goshng/all/polap/Flye/o/40-polishing/sort_241207_112408' -O bam -@ 4 -l 1 -m 1G -o '/home/goshng/all/polap/Flye/o/40-polishing/minimap_1.bam'
flye-minimap2 '/home/goshng/all/polap/Flye/o/40-polishing/filtered_contigs.fasta' '/home/goshng/all/polap/Flye/o/30-contigger/graph_final.fasta' -x map-pb -t 8 -a -p 0.5 -N 10 --sam-hit-only -L -K 1G -z 1000 -Q --secondary-seq -I 64G | flye-samtools view -T '/home/goshng/all/polap/Flye/o/40-polishing/filtered_contigs.fasta' -u - | flye-samtools sort -T '/home/goshng/all/polap/Flye/o/40-polishing/sort_241207_112414' -O bam -@ 4 -l 1 -m 1G -o '/home/goshng/all/polap/Flye/o/40-polishing/edges_aln.bam'
